# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='addmsg.proto',
  package='Test',
  serialized_pb='\n\x0c\x61\x64\x64msg.proto\x12\x04Test\"D\n\rAddMsgRequest\x12\x13\n\x0biSequenceID\x18\x01 \x02(\r\x12\x0e\n\x06param1\x18\x02 \x02(\r\x12\x0e\n\x06param2\x18\x03 \x02(\r\"O\n\x0c\x41\x64\x64MsgResult\x12\x13\n\x0biSequenceID\x18\x01 \x02(\r\x12\r\n\x05\x65rror\x18\x02 \x02(\x05\x12\x0e\n\x06\x65rrmsg\x18\x03 \x01(\t\x12\x0b\n\x03sum\x18\x04 \x01(\r')




_ADDMSGREQUEST = descriptor.Descriptor(
  name='AddMsgRequest',
  full_name='Test.AddMsgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='iSequenceID', full_name='Test.AddMsgRequest.iSequenceID', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='param1', full_name='Test.AddMsgRequest.param1', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='param2', full_name='Test.AddMsgRequest.param2', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=90,
)


_ADDMSGRESULT = descriptor.Descriptor(
  name='AddMsgResult',
  full_name='Test.AddMsgResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='iSequenceID', full_name='Test.AddMsgResult.iSequenceID', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='Test.AddMsgResult.error', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errmsg', full_name='Test.AddMsgResult.errmsg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sum', full_name='Test.AddMsgResult.sum', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=92,
  serialized_end=171,
)



class AddMsgRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDMSGREQUEST
  
  # @@protoc_insertion_point(class_scope:Test.AddMsgRequest)

class AddMsgResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDMSGRESULT
  
  # @@protoc_insertion_point(class_scope:Test.AddMsgResult)

# @@protoc_insertion_point(module_scope)
