// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addmsg.proto

#ifndef PROTOBUF_addmsg_2eproto__INCLUDED
#define PROTOBUF_addmsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace Test {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_addmsg_2eproto();
void protobuf_AssignDesc_addmsg_2eproto();
void protobuf_ShutdownFile_addmsg_2eproto();

class AddMsgRequest;
class AddMsgResult;

// ===================================================================

class AddMsgRequest : public ::google::protobuf::Message {
 public:
  AddMsgRequest();
  virtual ~AddMsgRequest();
  
  AddMsgRequest(const AddMsgRequest& from);
  
  inline AddMsgRequest& operator=(const AddMsgRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const AddMsgRequest& default_instance();
  
  void Swap(AddMsgRequest* other);
  
  // implements Message ----------------------------------------------
  
  AddMsgRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AddMsgRequest& from);
  void MergeFrom(const AddMsgRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 iSequenceID = 1;
  inline bool has_isequenceid() const;
  inline void clear_isequenceid();
  static const int kISequenceIDFieldNumber = 1;
  inline ::google::protobuf::uint32 isequenceid() const;
  inline void set_isequenceid(::google::protobuf::uint32 value);
  
  // required uint32 param1 = 2;
  inline bool has_param1() const;
  inline void clear_param1();
  static const int kParam1FieldNumber = 2;
  inline ::google::protobuf::uint32 param1() const;
  inline void set_param1(::google::protobuf::uint32 value);
  
  // required uint32 param2 = 3;
  inline bool has_param2() const;
  inline void clear_param2();
  static const int kParam2FieldNumber = 3;
  inline ::google::protobuf::uint32 param2() const;
  inline void set_param2(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:Test.AddMsgRequest)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::uint32 isequenceid_;
  ::google::protobuf::uint32 param1_;
  ::google::protobuf::uint32 param2_;
  friend void  protobuf_AddDesc_addmsg_2eproto();
  friend void protobuf_AssignDesc_addmsg_2eproto();
  friend void protobuf_ShutdownFile_addmsg_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static AddMsgRequest* default_instance_;
};
// -------------------------------------------------------------------

class AddMsgResult : public ::google::protobuf::Message {
 public:
  AddMsgResult();
  virtual ~AddMsgResult();
  
  AddMsgResult(const AddMsgResult& from);
  
  inline AddMsgResult& operator=(const AddMsgResult& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const AddMsgResult& default_instance();
  
  void Swap(AddMsgResult* other);
  
  // implements Message ----------------------------------------------
  
  AddMsgResult* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AddMsgResult& from);
  void MergeFrom(const AddMsgResult& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 iSequenceID = 1;
  inline bool has_isequenceid() const;
  inline void clear_isequenceid();
  static const int kISequenceIDFieldNumber = 1;
  inline ::google::protobuf::uint32 isequenceid() const;
  inline void set_isequenceid(::google::protobuf::uint32 value);
  
  // required int32 error = 2;
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 2;
  inline ::google::protobuf::int32 error() const;
  inline void set_error(::google::protobuf::int32 value);
  
  // optional string errmsg = 3;
  inline bool has_errmsg() const;
  inline void clear_errmsg();
  static const int kErrmsgFieldNumber = 3;
  inline const ::std::string& errmsg() const;
  inline void set_errmsg(const ::std::string& value);
  inline void set_errmsg(const char* value);
  inline void set_errmsg(const char* value, size_t size);
  inline ::std::string* mutable_errmsg();
  
  // optional uint32 sum = 4;
  inline bool has_sum() const;
  inline void clear_sum();
  static const int kSumFieldNumber = 4;
  inline ::google::protobuf::uint32 sum() const;
  inline void set_sum(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:Test.AddMsgResult)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::uint32 isequenceid_;
  ::google::protobuf::int32 error_;
  ::std::string* errmsg_;
  static const ::std::string _default_errmsg_;
  ::google::protobuf::uint32 sum_;
  friend void  protobuf_AddDesc_addmsg_2eproto();
  friend void protobuf_AssignDesc_addmsg_2eproto();
  friend void protobuf_ShutdownFile_addmsg_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static AddMsgResult* default_instance_;
};
// ===================================================================


// ===================================================================

// AddMsgRequest

// required uint32 iSequenceID = 1;
inline bool AddMsgRequest::has_isequenceid() const {
  return _has_bit(0);
}
inline void AddMsgRequest::clear_isequenceid() {
  isequenceid_ = 0u;
  _clear_bit(0);
}
inline ::google::protobuf::uint32 AddMsgRequest::isequenceid() const {
  return isequenceid_;
}
inline void AddMsgRequest::set_isequenceid(::google::protobuf::uint32 value) {
  _set_bit(0);
  isequenceid_ = value;
}

// required uint32 param1 = 2;
inline bool AddMsgRequest::has_param1() const {
  return _has_bit(1);
}
inline void AddMsgRequest::clear_param1() {
  param1_ = 0u;
  _clear_bit(1);
}
inline ::google::protobuf::uint32 AddMsgRequest::param1() const {
  return param1_;
}
inline void AddMsgRequest::set_param1(::google::protobuf::uint32 value) {
  _set_bit(1);
  param1_ = value;
}

// required uint32 param2 = 3;
inline bool AddMsgRequest::has_param2() const {
  return _has_bit(2);
}
inline void AddMsgRequest::clear_param2() {
  param2_ = 0u;
  _clear_bit(2);
}
inline ::google::protobuf::uint32 AddMsgRequest::param2() const {
  return param2_;
}
inline void AddMsgRequest::set_param2(::google::protobuf::uint32 value) {
  _set_bit(2);
  param2_ = value;
}

// -------------------------------------------------------------------

// AddMsgResult

// required uint32 iSequenceID = 1;
inline bool AddMsgResult::has_isequenceid() const {
  return _has_bit(0);
}
inline void AddMsgResult::clear_isequenceid() {
  isequenceid_ = 0u;
  _clear_bit(0);
}
inline ::google::protobuf::uint32 AddMsgResult::isequenceid() const {
  return isequenceid_;
}
inline void AddMsgResult::set_isequenceid(::google::protobuf::uint32 value) {
  _set_bit(0);
  isequenceid_ = value;
}

// required int32 error = 2;
inline bool AddMsgResult::has_error() const {
  return _has_bit(1);
}
inline void AddMsgResult::clear_error() {
  error_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 AddMsgResult::error() const {
  return error_;
}
inline void AddMsgResult::set_error(::google::protobuf::int32 value) {
  _set_bit(1);
  error_ = value;
}

// optional string errmsg = 3;
inline bool AddMsgResult::has_errmsg() const {
  return _has_bit(2);
}
inline void AddMsgResult::clear_errmsg() {
  if (errmsg_ != &_default_errmsg_) {
    errmsg_->clear();
  }
  _clear_bit(2);
}
inline const ::std::string& AddMsgResult::errmsg() const {
  return *errmsg_;
}
inline void AddMsgResult::set_errmsg(const ::std::string& value) {
  _set_bit(2);
  if (errmsg_ == &_default_errmsg_) {
    errmsg_ = new ::std::string;
  }
  errmsg_->assign(value);
}
inline void AddMsgResult::set_errmsg(const char* value) {
  _set_bit(2);
  if (errmsg_ == &_default_errmsg_) {
    errmsg_ = new ::std::string;
  }
  errmsg_->assign(value);
}
inline void AddMsgResult::set_errmsg(const char* value, size_t size) {
  _set_bit(2);
  if (errmsg_ == &_default_errmsg_) {
    errmsg_ = new ::std::string;
  }
  errmsg_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AddMsgResult::mutable_errmsg() {
  _set_bit(2);
  if (errmsg_ == &_default_errmsg_) {
    errmsg_ = new ::std::string;
  }
  return errmsg_;
}

// optional uint32 sum = 4;
inline bool AddMsgResult::has_sum() const {
  return _has_bit(3);
}
inline void AddMsgResult::clear_sum() {
  sum_ = 0u;
  _clear_bit(3);
}
inline ::google::protobuf::uint32 AddMsgResult::sum() const {
  return sum_;
}
inline void AddMsgResult::set_sum(::google::protobuf::uint32 value) {
  _set_bit(3);
  sum_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Test

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_addmsg_2eproto__INCLUDED
